/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#7bd1fa",
        "outline": "#567997",
        "on-primary-fixed": "#00121d",
        "surface-container-lowest": "#000000",
        "secondary-dim": "#cad5ed",
        "on-secondary-fixed-variant": "#515c70",
        "inverse-on-surface": "#345875",
        "error-dim": "#d7383b",
        "error": "#ff716c",
        "primary-container": "#22b1ec",
        "on-tertiary-fixed-variant": "#004f69",
        "on-background": "#d1e8ff",
        "on-tertiary-container": "#00465d",
        "tertiary": "#9bddff",
        "tertiary-container": "#7bd1fa",
        "inverse-surface": "#f7f9ff",
        "inverse-primary": "#00668b",
        "on-surface": "#d1e8ff",
        "surface-container-highest": "#002840",
        "surface-tint": "#3bbffa",
        "on-secondary-fixed": "#354053",
        "on-primary-container": "#002b3d",
        "surface-bright": "#002f4a",
        "on-primary": "#00374d",
        "error-container": "#9f0519",
        "on-secondary-container": "#c5d1e8",
        "surface-variant": "#002840",
        "on-tertiary-fixed": "#003041",
        "on-primary-fixed-variant": "#003a50",
        "background": "#00101d",
        "primary-fixed": "#2db7f2",
        "secondary-fixed": "#d8e3fb",
        "outline-variant": "#264b67",
        "primary": "#3bbffa",
        "on-secondary": "#475266",
        "on-error": "#490006",
        "primary-fixed-dim": "#05a9e3",
        "tertiary-fixed-dim": "#6cc3eb",
        "surface-dim": "#00101d",
        "on-surface-variant": "#8bafcf",
        "secondary-fixed-dim": "#cad5ed",
        "tertiary-dim": "#6cc3eb",
        "surface": "#00101d",
        "secondary-container": "#3c475a",
        "secondary": "#d8e3fb",
        "surface-container-high": "#002237",
        "primary-dim": "#05a9e3",
        "on-tertiary": "#004f69",
        "surface-container-low": "#001524",
        "on-error-container": "#ffa8a3",
        "surface-container": "#001b2e"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    }
  },
  plugins: [],
};
